/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kovtun.WorkTimeMap.UI;

import com.kovtun.WorkTimeMap.Models.db.Action;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author kovtun
 */
public class ActionsDialog extends javax.swing.JDialog {
    private List<Action> actionList;
    /**
     * Creates new form ActionsDialog
     */
    public ActionsDialog(java.awt.Frame parent, boolean modal,List<Action> actionList) {
        super(parent, modal);
        this.actionList=actionList;
        initComponents();
        ((JPanel)userForm1.getComponents()[2]).remove(((JPanel)userForm1.getComponents()[2]).getComponents()[2]);
    }
    private DefaultListModel convertMassive(){
        DefaultListModel<String> model=new DefaultListModel();
        
        for(Action a:actionList)
            model.addElement(a.getName());
        
        return model;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        userForm1 = new com.kovtun.WorkTimeMap.UI.UserForm();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setModel(convertMassive());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(userForm1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(!evt.getValueIsAdjusting()&&jList1.getSelectedIndex()!=-1&&actionList.size()>jList1.getSelectedIndex())
                    setDataToComponents(actionList.get(jList1.getSelectedIndex()));
    }//GEN-LAST:event_jList1ValueChanged
    private void setDataToComponents(Action action){
        userForm1.nameTextField.setText(action==null?"":action.getName());
        userForm1.descriptionArea.setText(action==null?"":action.getDescription());
        userForm1.CommentArea.setText(action==null?"":action.getComment());
        userForm1.startTimeLabel.setText(action==null?"":new SimpleDateFormat("HH:mm").format(action.getStartTime()));
        userForm1.stopTimeLabel.setText(action==null?"":action.getStopTime()!=null?new SimpleDateFormat("HH:mm").format(action.getStopTime()):"Еще не закончино!");
        userForm1.projectLabel.setText(action==null?"":action.getProjectId().getName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.kovtun.WorkTimeMap.UI.UserForm userForm1;
    // End of variables declaration//GEN-END:variables
}
