/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kovtun.WorkTimeMap.UI;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.kovtun.WorkTimeMap.CallBacks.ActionDialogCallBack;
import com.kovtun.WorkTimeMap.Models.db.Action;
import com.kovtun.WorkTimeMap.Models.db.Project;
import com.kovtun.WorkTimeMap.Values;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kovtun
 */
public class CreateActionDialog extends javax.swing.JDialog {
    private Action action=null;
    private List<Project> projects;
    private DefaultComboBoxModel model;
    private ActionDialogCallBack callback;
    /**
     * Creates new form CreateActionDialog
     */
    public CreateActionDialog(java.awt.Frame parent, boolean modal,ActionDialogCallBack callback,Action action, List<Project> projects) {
        super(parent, modal);
        this.callback=callback;
        this.action=action;
        this.projects=projects;
        
        model=new DefaultComboBoxModel(projects.toArray());
        initComponents();
        if(action!=null){
            setDataToView();
            jCheckBox1.setSelected(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CommentArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TimePickerSettings timeSettings=new TimePickerSettings();
        DatePickerSettings dateSettings=new DatePickerSettings();
        dateSettings.setAllowEmptyDates(false);
        timeSettings.setDisplaySpinnerButtons(true);
        timeSettings.setInitialTimeToNow();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker(dateSettings, timeSettings);
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8_ = new javax.swing.JLabel();
        TimePickerSettings timeSettings1=new TimePickerSettings();
        DatePickerSettings dateSettings1=new DatePickerSettings();
        dateSettings1.setAllowEmptyDates(false);
        timeSettings1.setDisplaySpinnerButtons(true);
        timeSettings1.setInitialTimeToNow();
        dateTimePicker2 = new com.github.lgooddatepicker.components.DateTimePicker(dateSettings1, timeSettings1);
        jPanel7 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Действие");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(520, 2147483647));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 300));

        jLabel1.setText("Проект:");
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel2.setText("Имя:");
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        nameTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jComboBox1.setModel(model);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 630, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jLabel3.setText("Описание:");
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        descriptionArea.setColumns(20);
        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(5);
        descriptionArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descriptionArea);

        jLabel4.setText("Комментарий:");

        CommentArea.setColumns(20);
        CommentArea.setLineWrap(true);
        CommentArea.setRows(5);
        CommentArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(CommentArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(dateTimePicker1, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Начало: ");
        jPanel5.add(jLabel5, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel8_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8_.setText("Завершение: ");
        jPanel6.add(jLabel8_, java.awt.BorderLayout.WEST);
        jPanel6.add(dateTimePicker2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.EAST);

        okButton.setText("OK");
        okButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        changeButton.setText("Отмена");
        changeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Завершенный проект");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(changeButton)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        if (!nameTextField.getText().isEmpty()&&!descriptionArea.getText().isEmpty()){
            if(action==null){
               action=new Action();
               action.setName(nameTextField.getText());
               action.setDescription(descriptionArea.getText());
               action.setComment(CommentArea.getText());
               action.setUserId(Values.user);
               action.setProjectId(projects.get(jComboBox1.getSelectedIndex()));
               action.setStartTime(Date.from(dateTimePicker1.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant()));
               if(jCheckBox1.isSelected())
                    action.setStopTime(Date.from(dateTimePicker2.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant()));
               callback.createAction(action);
               dispose();
            }else{
               action.setName(nameTextField.getText());
               action.setDescription(descriptionArea.getText());
               action.setComment(CommentArea.getText());
               action.setUserId(Values.user);
               action.setProjectId(projects.get(jComboBox1.getSelectedIndex()));
               action.setStartTime(Date.from(dateTimePicker1.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant()));
               if(jCheckBox1.isSelected())
                    action.setStopTime(Date.from(dateTimePicker2.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant()));
               else
                   action.setStopTime(null);
               callback.updateAction(action);
               dispose();
            }
        }else {
            JOptionPane.showMessageDialog(this, "Не все поля заполнены","Ошибка", JOptionPane.PLAIN_MESSAGE);

        }
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_changeButtonActionPerformed

    private void setDataToView() {
        for(int i=0;i<projects.size();i++)
            if(projects.get(i).getId()==action.getProjectId().getId())
                jComboBox1.setSelectedIndex(i);

        nameTextField.setText(action.getName());
        descriptionArea.setText(action.getDescription());
        CommentArea.setText(action.getComment());
        Calendar calendar=new Calendar.Builder().setInstant(action.getStartTime()).build();
        dateTimePicker1.setDateTimePermissive(LocalDateTime.ofInstant(action.getStartTime().toInstant(), ZoneId.systemDefault()));
        if(action.getStopTime()!=null)
            dateTimePicker2.setDateTimePermissive(LocalDateTime.ofInstant(action.getStopTime().toInstant(), ZoneId.systemDefault()));
        //startTimeLabel.setText(new SimpleDateFormat("dd.MM.yyyy HH:mm").format(action.getStartTime()));
        //stopTimeLabel.setText(action.getStopTime()!=null?new SimpleDateFormat("dd.MM.yyyy HH:mm").format(action.getStopTime()):"Еще не завершено!");
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea CommentArea;
    public javax.swing.JButton changeButton;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker2;
    public javax.swing.JTextArea descriptionArea;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField nameTextField;
    public javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
