/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kovtun.WorkTimeMap.UI;

import com.kovtun.WorkTimeMap.Models.db.User;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author kovtun
 */
public class UserManagerDialog extends javax.swing.JDialog {
    private List<User> userList;
    private EntityManager em;
    /**
     * Creates new form UserManagerDialog
     */
    public UserManagerDialog(java.awt.Frame parent, boolean modal,EntityManager em) {
        super(parent, modal);
        this.em=em;
        this.userList=em.createNamedQuery("User.findAll", User.class).getResultList();
        initComponents();
        setDataChangeListeners();
    }
    
    private DefaultListModel<String> initUsersModel(){
        DefaultListModel<String> model=new DefaultListModel();
        
        for(User u:userList)
            model.addElement(u.getFio());
        
        return model;
    }
    private void setDataToViews(int index){
        deleteButton.setEnabled(true);
        cancelButton.setEnabled(false);
        saveButton.setEnabled(false);
        
        passwordField.setEnabled(true);
        loginField.setEnabled(true);
        nameField.setEnabled(true);
        RBox.setEnabled(true);
        
        passwordField.setText(userList.get(index).getPassword());
        loginField.setText(userList.get(index).getLogin());
        nameField.setText(userList.get(index).getFio());
        RBox.setSelectedIndex(userList.get(index).getRights()-1);
    }
    
    private void clearAllView(){
        deleteButton.setEnabled(false);
        cancelButton.setEnabled(false);
        saveButton.setEnabled(false);
        
        passwordField.setEnabled(false);
        loginField.setEnabled(false);
        nameField.setEnabled(false);
        RBox.setEnabled(false);
        
        passwordField.setText("");
        loginField.setText("");
        nameField.setText("");
        RBox.setSelectedIndex(0);
    }
    
    private void setDataChangeListeners(){
        nameField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              userChangeListener();
            }
            public void removeUpdate(DocumentEvent e) {
              userChangeListener();
            }
            public void insertUpdate(DocumentEvent e) {
              userChangeListener();
            }
        });
        passwordField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              userChangeListener();
            }
            public void removeUpdate(DocumentEvent e) {
              userChangeListener();
            }
            public void insertUpdate(DocumentEvent e) {
              userChangeListener();
            }
        });
        loginField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              userChangeListener();
            }
            public void removeUpdate(DocumentEvent e) {
              userChangeListener();
            }
            public void insertUpdate(DocumentEvent e) {
              userChangeListener();
            }
        });
    }
    
    private void refresh(int position){
        jList1.setModel(initUsersModel());
        if(position!=-1&&userList.size()>position)
            jList1.setSelectedIndex(position);
        else if(userList.size()>0)
            jList1.setSelectedIndex(0);
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Менеджер пользователей");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1.setModel(initUsersModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("ФИО:");

        nameField.setEnabled(false);

        jLabel2.setText("Логин:");

        loginField.setEnabled(false);

        jLabel3.setText("Пароль:");

        passwordField.setEnabled(false);

        jLabel4.setText("Права:");

        RBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Админ", "Менеджер", "Рабочий" }));
        RBox.setEnabled(false);
        RBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBoxActionPerformed(evt);
            }
        });

        cancelButton.setText("Отмена");

        saveButton.setText("Сохранить");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteButton.setText("-");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Пользователи");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nameField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deleteButton)
                    .addComponent(addButton)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(saveButton)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(!evt.getValueIsAdjusting()&&jList1.getSelectedIndex()!=-1){
            setDataToViews(jList1.getSelectedIndex());
        }else if(!evt.getValueIsAdjusting()&&jList1.getSelectedIndex()==-1){
            clearAllView();
        }
    }//GEN-LAST:event_jList1ValueChanged
    private void userChangeListener(){
        if(jList1.getSelectedIndex()>=0){
            if((!userList.get(jList1.getSelectedIndex()).getFio().equals(nameField.getText()))||(!userList.get(jList1.getSelectedIndex()).getLogin().equals(loginField.getText()))
                ||(!userList.get(jList1.getSelectedIndex()).getPassword().equals(passwordField.getText()))||(userList.get(jList1.getSelectedIndex()).getRights()!=(RBox.getSelectedIndex()+1))){
                cancelButton.setEnabled(true);
                saveButton.setEnabled(true);
            }else{
                cancelButton.setEnabled(false);
                saveButton.setEnabled(false);
            }
        }else{
            if(!nameField.getText().isEmpty()&&nameField.getText().length()>4&&!loginField.getText().isEmpty()&&loginField.getText().length()>4
                    &&!passwordField.getText().isEmpty()&&passwordField.getText().length()>4){
                cancelButton.setEnabled(true);
                saveButton.setEnabled(true);
            }else{
                cancelButton.setEnabled(true);
                saveButton.setEnabled(false);
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBoxActionPerformed
        userChangeListener();
    }//GEN-LAST:event_RBoxActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(jList1.getSelectedIndex()!=-1){
            int position=jList1.getSelectedIndex();
            jList1.clearSelection();
            em.getTransaction().begin();
            em.remove(userList.get(position));
            em.getTransaction().commit();
            userList.remove(userList.get(position));
            refresh(position);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        jList1.clearSelection();
        
        deleteButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(false);
        
        passwordField.setEnabled(true);
        loginField.setEnabled(true);
        nameField.setEnabled(true);
        RBox.setEnabled(true);
        
        passwordField.setText("");
        loginField.setText("");
        nameField.setText("");
        RBox.setSelectedIndex(0);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(jList1.getSelectedIndex()>=0){
            
            int position=jList1.getSelectedIndex();
            userList.get(position).setFio(nameField.getText());
            userList.get(position).setLogin(loginField.getText());
            userList.get(position).setPassword(passwordField.getText());
            userList.get(position).setRights(RBox.getSelectedIndex()+1);
            jList1.clearSelection();
            em.getTransaction().begin();
            em.merge(userList.get(position));
            em.getTransaction().commit();
            
            refresh(position);
        }else{
            User u=new User(nameField.getText(),loginField.getText(),passwordField.getText(),RBox.getSelectedIndex()+1);
            em.getTransaction().begin();
            em.merge(u);
            em.getTransaction().commit();
            userList.add(u);
            refresh(userList.size()-1);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RBox;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
